language: c++

os:
  - linux
compiler:
  - clang
  - gcc

before_install:
  # Install compression packages
  - sudo apt-get -qq update
  - sudo apt-get install -y zlib1g-dev bzip2

before_script:
  - mkdir -p build
  - pushd build
  - cmake ..

script:
  - make
  - tests/run-tests tests/data

matrix:
  exclude:
    - os: linux
      compiler: clang
