language: c++

os:
  - linux
compiler:
  - clang
  - gcc

before_install:
  # Install from a fork until 
  - git clone -b easier-to-inherit https://github.com/drdavella/yaml-cpp
  - mkdir -p yaml-cpp/build
  - pushd yaml-cpp/build
  - cmake ..
  - make
  - make install
  - popd

before_script:
  - mkdir -p build
  - pushd build
  - cmake ..

script:
  - make
  - tests/run-tests tests/data

matrix:
  exclude:
    - os: linux
      compiler: clang
